param(
  [string]$ProjectRoot = "D:\Projects\Endless Fantasy",
  [string]$OutRoot = "D:\Projects\Endless Fantasy\src\assets",
  [string]$PreviewRoot = "D:\Projects\Endless Fantasy\src\assets\source\art_import\previews"
)

$ErrorActionPreference = "Stop"

function Get-Magick {
  $cmd = Get-Command magick -ErrorAction SilentlyContinue
  if ($cmd) { return $cmd.Source }
  $fallback = "D:\Tools\ImageMagick\magick.exe"
  if (Test-Path $fallback) { return $fallback }
  throw "ImageMagick 'magick' was not found."
}

function New-Preview([string]$Name, [string[]]$Files, [string]$Thumb, [string]$Tile = "6x") {
  if (!$Files -or $Files.Count -eq 0) { return }
  $preview = Join-Path $PreviewRoot $Name
  & $script:Magick montage @Files -background "#101827" -fill "#f5f2df" -stroke "#050812" -strokewidth 2 -label "%t" -thumbnail $Thumb -geometry "+14+22" -tile $Tile $preview
  Write-Host "preview $Name"
}

$script:Magick = Get-Magick
New-Item -ItemType Directory -Force -Path $PreviewRoot | Out-Null

New-Preview "world_tiles_preview.png" (Get-ChildItem -Path (Join-Path $OutRoot "tiles\world") -Filter "*.png" | Sort-Object Name | ForEach-Object FullName) "64x64" "5x"
New-Preview "markers_preview.png" (Get-ChildItem -Path (Join-Path $OutRoot "tiles\markers") -Filter "*.png" | Sort-Object Name | ForEach-Object FullName) "80x80" "5x"
New-Preview "characters_preview.png" (Get-ChildItem -Path (Join-Path $OutRoot "characters") -Filter "*.png" | Sort-Object Name | ForEach-Object FullName) "120x120" "4x"
New-Preview "portraits_preview.png" (Get-ChildItem -Path (Join-Path $OutRoot "portraits") -Filter "*.png" | Sort-Object Name | ForEach-Object FullName) "96x120" "3x"
New-Preview "enemies_preview.png" (Get-ChildItem -Path (Join-Path $OutRoot "enemies\common") -Filter "*.png" | Sort-Object Name | ForEach-Object FullName) "112x112" "4x"
New-Preview "bosses_preview.png" (Get-ChildItem -Path (Join-Path $OutRoot "enemies\bosses") -Filter "*.png" | Sort-Object Name | ForEach-Object FullName) "160x160" "3x"
New-Preview "ui_preview.png" (Get-ChildItem -Path (Join-Path $OutRoot "ui") -Filter "*.png" | Sort-Object Name | ForEach-Object FullName) "120x80" "4x"
New-Preview "battle_backgrounds_preview.png" (Get-ChildItem -Path (Join-Path $OutRoot "battle\backgrounds") -Filter "*.png" | Sort-Object Name | ForEach-Object FullName) "220x90" "2x"

$report = @'
# Assets V2 Quality Report

Generated by `tools/art_import/generate_asset_previews.ps1`.

## Wired candidates

- World tiles: clean label-free crops from `world_terrain_sheet.png`; resized to 32x32 for the current grid.
- Location markers: transparent, resized marker icons from the high-quality extracted location PNGs.
- Characters: map sheets, battle stances, and portraits cropped from master character sheets rather than the label-contaminated extracted snippets.
- Common enemies: first twelve roster monsters cropped from `monster_roster_master.png`; later-region enemies remain old/fallback assets.
- Bosses: five clean boss crops mapped to the game's original boss IDs.
- Battle backgrounds: six opaque 960x390 battle backdrops resized/cropped from the separated background panels.
- UI: a new compact 9-slice source, cursor, HP/MP bars, and button crops from `battle_ui_master.png`.

## Source-only / needs cleanup

- `00_original_collages/*` remain references only; they contain labels, multiple unrelated assets, and sheet backgrounds.
- `location_markers_sheet.png`, `world_tileset_master.png`, `monster_roster_master.png`, `boss_roster_master.png`, and character master sheets are copied to `src/assets/source/art_import/source_sheets` for provenance only.
- The pre-separated common enemy PNGs in `D:\Projects\new_artwork\05_enemies\common` were not trusted because several are cropped poorly or still carry sheet background remnants.
- The pre-separated character `battle_sprite.png` files were not trusted because labels and edge cuts remain visible.
- Tide/world later-region normal enemies not present in the new common roster use existing runtime fallbacks.
- rembg default path/model: `D:\tools\rembg\venv_rembg\Scripts\rembg.exe` with `birefnet-general`.
- ONNX Runtime providers detected in the rembg venv: `DmlExecutionProvider`, `CPUExecutionProvider`; this is the AMD/Windows DirectML setup, not NVIDIA/CUDA.
- rembg supported fallback order: `birefnet-massive`, `u2net`, `isnet-general-use`, then `u2netp` for fast icon cleanup only.
- rembg was promoted only for `prop_crate.png`, `prop_barrel.png`, `prop_lamp.png`, and `prop_rug.png`; color-key stayed cleaner for characters, portraits, battle sprites, enemies, bosses, markers, service signs, cursors, buttons, and UI bars.

## Manual inspection notes

- Review all `src/assets/source/art_import/previews/*.png` after extraction before expanding the crop maps.
- Enemy ground shadows are retained from the source art where they are embedded in the sprite crop; battle code still adds a soft runtime shadow.
- UI text remains live Phaser text; labels from the UI sheet are not baked into runtime panels.
'@

Set-Content -Path (Join-Path $PreviewRoot "QUALITY_REPORT.md") -Value $report -Encoding UTF8
Write-Host "quality report src\assets\source\art_import\previews\QUALITY_REPORT.md"
Write-Host "ImageMagick: $script:Magick"
