// Generated by tools/art_import/import_character_sprites.mjs. Do not hand-edit frame measurements.
export const CHARACTER_SPRITES = {
  "fighter": {
    "image": "assets_v2/characters/classes/fighter_normalized.png",
    "textureKey": "class_fighter_sheet",
    "source": {
      "originalFile": "D:/Tools/rembg/bg_output/fighter.png",
      "copiedFile": "assets_v2/source_sheets/class_sprites/fighter.png",
      "sheetWidth": 1983,
      "sheetHeight": 793,
      "sourceColumns": 5,
      "sourceRows": 2,
      "splitMethod": "rounded proportional 5x2 cell boundaries from the source sheet dimensions"
    },
    "grid": {
      "columns": 5,
      "rows": 2,
      "cellWidth": 704,
      "cellHeight": 512,
      "sheetWidth": 3520,
      "sheetHeight": 1024
    },
    "anchor": {
      "bodyCenterX": 352,
      "feetBaselineY": 464
    },
    "frameOrder": [
      "attack_windup_left",
      "attack_release_left",
      "walk_down_a",
      "walk_down_b",
      "walk_left_a",
      "walk_left_b",
      "walk_right_a",
      "walk_right_b",
      "walk_up_a",
      "walk_up_b"
    ],
    "frames": {
      "attack_windup_left": {
        "row": 0,
        "col": 0,
        "index": 0,
        "sourceIndex": 0,
        "sourceRow": 0,
        "sourceCol": 0,
        "sourceRect": {
          "x": 0,
          "y": 0,
          "width": 397,
          "height": 397
        },
        "sourceAlphaBBox": {
          "x": 104,
          "y": 73,
          "width": 293,
          "height": 285
        },
        "normalizedPlacement": {
          "x": 236,
          "y": 180,
          "width": 293,
          "height": 285
        },
        "sourceAnchor": {
          "bodyCenterX": 220,
          "feetBaselineY": 357
        },
        "rationale": "First attack pose; character faces left.",
        "warnings": [
          "Alpha bbox touches source cell boundary; verify proportional split."
        ]
      },
      "attack_release_left": {
        "row": 0,
        "col": 1,
        "index": 1,
        "sourceIndex": 1,
        "sourceRow": 0,
        "sourceCol": 1,
        "sourceRect": {
          "x": 397,
          "y": 0,
          "width": 396,
          "height": 397
        },
        "sourceAlphaBBox": {
          "x": 397,
          "y": 75,
          "width": 387,
          "height": 283
        },
        "normalizedPlacement": {
          "x": 127,
          "y": 182,
          "width": 387,
          "height": 283
        },
        "sourceAnchor": {
          "bodyCenterX": 622,
          "feetBaselineY": 357
        },
        "rationale": "Second attack/release pose; effect extends left.",
        "warnings": [
          "Alpha bbox touches source cell boundary; verify proportional split."
        ]
      },
      "walk_down_a": {
        "row": 0,
        "col": 2,
        "index": 2,
        "sourceIndex": 2,
        "sourceRow": 0,
        "sourceCol": 2,
        "sourceRect": {
          "x": 793,
          "y": 0,
          "width": 397,
          "height": 397
        },
        "sourceAlphaBBox": {
          "x": 867,
          "y": 62,
          "width": 238,
          "height": 301
        },
        "normalizedPlacement": {
          "x": 219,
          "y": 164,
          "width": 238,
          "height": 301
        },
        "sourceAnchor": {
          "bodyCenterX": 1000,
          "feetBaselineY": 362
        },
        "rationale": "First front-facing walking pose in top row.",
        "warnings": []
      },
      "walk_down_b": {
        "row": 0,
        "col": 3,
        "index": 3,
        "sourceIndex": 3,
        "sourceRow": 0,
        "sourceCol": 3,
        "sourceRect": {
          "x": 1190,
          "y": 0,
          "width": 396,
          "height": 397
        },
        "sourceAlphaBBox": {
          "x": 1227,
          "y": 62,
          "width": 238,
          "height": 301
        },
        "normalizedPlacement": {
          "x": 217,
          "y": 164,
          "width": 238,
          "height": 301
        },
        "sourceAnchor": {
          "bodyCenterX": 1362,
          "feetBaselineY": 362
        },
        "rationale": "Second front-facing walking pose in top row.",
        "warnings": []
      },
      "walk_left_a": {
        "row": 0,
        "col": 4,
        "index": 4,
        "sourceIndex": 4,
        "sourceRow": 0,
        "sourceCol": 4,
        "sourceRect": {
          "x": 1586,
          "y": 0,
          "width": 397,
          "height": 397
        },
        "sourceAlphaBBox": {
          "x": 1609,
          "y": 62,
          "width": 253,
          "height": 301
        },
        "normalizedPlacement": {
          "x": 205,
          "y": 164,
          "width": 253,
          "height": 301
        },
        "sourceAnchor": {
          "bodyCenterX": 1756,
          "feetBaselineY": 362
        },
        "rationale": "First side-facing walk pose after down frames; assigned left by sheet order.",
        "warnings": []
      },
      "walk_left_b": {
        "row": 1,
        "col": 0,
        "index": 5,
        "sourceIndex": 5,
        "sourceRow": 1,
        "sourceCol": 0,
        "sourceRect": {
          "x": 0,
          "y": 397,
          "width": 397,
          "height": 396
        },
        "sourceAlphaBBox": {
          "x": 56,
          "y": 429,
          "width": 268,
          "height": 298
        },
        "normalizedPlacement": {
          "x": 198,
          "y": 167,
          "width": 268,
          "height": 298
        },
        "sourceAnchor": {
          "bodyCenterX": 210,
          "feetBaselineY": 726
        },
        "rationale": "Second side-facing walk pose; assigned left by sheet order.",
        "warnings": []
      },
      "walk_right_a": {
        "row": 1,
        "col": 1,
        "index": 6,
        "sourceIndex": 6,
        "sourceRow": 1,
        "sourceCol": 1,
        "sourceRect": {
          "x": 397,
          "y": 397,
          "width": 396,
          "height": 396
        },
        "sourceAlphaBBox": {
          "x": 477,
          "y": 425,
          "width": 266,
          "height": 302
        },
        "normalizedPlacement": {
          "x": 243,
          "y": 163,
          "width": 266,
          "height": 302
        },
        "sourceAnchor": {
          "bodyCenterX": 586,
          "feetBaselineY": 726
        },
        "rationale": "Next side-facing walk pose; assigned right by sheet order.",
        "warnings": []
      },
      "walk_right_b": {
        "row": 1,
        "col": 2,
        "index": 7,
        "sourceIndex": 7,
        "sourceRow": 1,
        "sourceCol": 2,
        "sourceRect": {
          "x": 793,
          "y": 397,
          "width": 397,
          "height": 396
        },
        "sourceAlphaBBox": {
          "x": 869,
          "y": 428,
          "width": 246,
          "height": 300
        },
        "normalizedPlacement": {
          "x": 247,
          "y": 165,
          "width": 246,
          "height": 300
        },
        "sourceAnchor": {
          "bodyCenterX": 974,
          "feetBaselineY": 727
        },
        "rationale": "Final side-facing walk pose; assigned right by sheet order.",
        "warnings": []
      },
      "walk_up_a": {
        "row": 1,
        "col": 3,
        "index": 8,
        "sourceIndex": 8,
        "sourceRow": 1,
        "sourceCol": 3,
        "sourceRect": {
          "x": 1190,
          "y": 397,
          "width": 396,
          "height": 396
        },
        "sourceAlphaBBox": {
          "x": 1271,
          "y": 424,
          "width": 238,
          "height": 303
        },
        "normalizedPlacement": {
          "x": 258,
          "y": 162,
          "width": 238,
          "height": 303
        },
        "sourceAnchor": {
          "bodyCenterX": 1365,
          "feetBaselineY": 726
        },
        "rationale": "First back-facing/up walking pose.",
        "warnings": []
      },
      "walk_up_b": {
        "row": 1,
        "col": 4,
        "index": 9,
        "sourceIndex": 9,
        "sourceRow": 1,
        "sourceCol": 4,
        "sourceRect": {
          "x": 1586,
          "y": 397,
          "width": 397,
          "height": 396
        },
        "sourceAlphaBBox": {
          "x": 1653,
          "y": 425,
          "width": 238,
          "height": 302
        },
        "normalizedPlacement": {
          "x": 259,
          "y": 163,
          "width": 238,
          "height": 302
        },
        "sourceAnchor": {
          "bodyCenterX": 1746,
          "feetBaselineY": 726
        },
        "rationale": "Second back-facing/up walking pose.",
        "warnings": []
      }
    },
    "notes": [
      "Source alpha channel was used as-is; no rembg, background removal, or chroma key was run.",
      "All frames share a fixed normalized body center and feet baseline.",
      "Attack frames use lower-body alpha median anchors so weapon/effect pixels do not pull the body anchor.",
      "Side left/right categories preserve the source sheet order."
    ]
  },
  "priest": {
    "image": "assets_v2/characters/classes/priest_normalized.png",
    "textureKey": "class_priest_sheet",
    "source": {
      "originalFile": "D:/Tools/rembg/bg_output/priest.png",
      "copiedFile": "assets_v2/source_sheets/class_sprites/priest.png",
      "sheetWidth": 1983,
      "sheetHeight": 793,
      "sourceColumns": 5,
      "sourceRows": 2,
      "splitMethod": "rounded proportional 5x2 cell boundaries from the source sheet dimensions"
    },
    "grid": {
      "columns": 5,
      "rows": 2,
      "cellWidth": 704,
      "cellHeight": 512,
      "sheetWidth": 3520,
      "sheetHeight": 1024
    },
    "anchor": {
      "bodyCenterX": 352,
      "feetBaselineY": 464
    },
    "frameOrder": [
      "attack_windup_left",
      "attack_release_left",
      "walk_down_a",
      "walk_down_b",
      "walk_left_a",
      "walk_left_b",
      "walk_right_a",
      "walk_right_b",
      "walk_up_a",
      "walk_up_b"
    ],
    "frames": {
      "attack_windup_left": {
        "row": 0,
        "col": 0,
        "index": 0,
        "sourceIndex": 0,
        "sourceRow": 0,
        "sourceCol": 0,
        "sourceRect": {
          "x": 0,
          "y": 0,
          "width": 397,
          "height": 397
        },
        "sourceAlphaBBox": {
          "x": 126,
          "y": 87,
          "width": 219,
          "height": 259
        },
        "normalizedPlacement": {
          "x": 224,
          "y": 206,
          "width": 219,
          "height": 259
        },
        "sourceAnchor": {
          "bodyCenterX": 254,
          "feetBaselineY": 345
        },
        "rationale": "First attack pose; character faces left.",
        "warnings": []
      },
      "attack_release_left": {
        "row": 0,
        "col": 1,
        "index": 1,
        "sourceIndex": 1,
        "sourceRow": 0,
        "sourceCol": 1,
        "sourceRect": {
          "x": 397,
          "y": 0,
          "width": 396,
          "height": 397
        },
        "sourceAlphaBBox": {
          "x": 426,
          "y": 113,
          "width": 358,
          "height": 236
        },
        "normalizedPlacement": {
          "x": 82,
          "y": 229,
          "width": 358,
          "height": 236
        },
        "sourceAnchor": {
          "bodyCenterX": 696,
          "feetBaselineY": 348
        },
        "rationale": "Second attack/release pose; effect extends left.",
        "warnings": []
      },
      "walk_down_a": {
        "row": 0,
        "col": 2,
        "index": 2,
        "sourceIndex": 2,
        "sourceRow": 0,
        "sourceCol": 2,
        "sourceRect": {
          "x": 793,
          "y": 0,
          "width": 397,
          "height": 397
        },
        "sourceAlphaBBox": {
          "x": 911,
          "y": 96,
          "width": 169,
          "height": 254
        },
        "normalizedPlacement": {
          "x": 258,
          "y": 211,
          "width": 169,
          "height": 254
        },
        "sourceAnchor": {
          "bodyCenterX": 1005,
          "feetBaselineY": 349
        },
        "rationale": "First front-facing walking pose in top row.",
        "warnings": []
      },
      "walk_down_b": {
        "row": 0,
        "col": 3,
        "index": 3,
        "sourceIndex": 3,
        "sourceRow": 0,
        "sourceCol": 3,
        "sourceRect": {
          "x": 1190,
          "y": 0,
          "width": 396,
          "height": 397
        },
        "sourceAlphaBBox": {
          "x": 1273,
          "y": 99,
          "width": 161,
          "height": 251
        },
        "normalizedPlacement": {
          "x": 264,
          "y": 214,
          "width": 161,
          "height": 251
        },
        "sourceAnchor": {
          "bodyCenterX": 1361,
          "feetBaselineY": 349
        },
        "rationale": "Second front-facing walking pose in top row.",
        "warnings": []
      },
      "walk_left_a": {
        "row": 0,
        "col": 4,
        "index": 4,
        "sourceIndex": 4,
        "sourceRow": 0,
        "sourceCol": 4,
        "sourceRect": {
          "x": 1586,
          "y": 0,
          "width": 397,
          "height": 397
        },
        "sourceAlphaBBox": {
          "x": 1673,
          "y": 96,
          "width": 162,
          "height": 253
        },
        "normalizedPlacement": {
          "x": 259,
          "y": 212,
          "width": 162,
          "height": 253
        },
        "sourceAnchor": {
          "bodyCenterX": 1766,
          "feetBaselineY": 348
        },
        "rationale": "First side-facing walk pose after down frames; assigned left by sheet order.",
        "warnings": []
      },
      "walk_left_b": {
        "row": 1,
        "col": 0,
        "index": 5,
        "sourceIndex": 5,
        "sourceRow": 1,
        "sourceCol": 0,
        "sourceRect": {
          "x": 0,
          "y": 397,
          "width": 397,
          "height": 396
        },
        "sourceAlphaBBox": {
          "x": 165,
          "y": 421,
          "width": 155,
          "height": 255
        },
        "normalizedPlacement": {
          "x": 267,
          "y": 210,
          "width": 155,
          "height": 255
        },
        "sourceAnchor": {
          "bodyCenterX": 250,
          "feetBaselineY": 675
        },
        "rationale": "Second side-facing walk pose; assigned left by sheet order.",
        "warnings": []
      },
      "walk_right_a": {
        "row": 1,
        "col": 1,
        "index": 6,
        "sourceIndex": 6,
        "sourceRow": 1,
        "sourceCol": 1,
        "sourceRect": {
          "x": 397,
          "y": 397,
          "width": 396,
          "height": 396
        },
        "sourceAlphaBBox": {
          "x": 572,
          "y": 428,
          "width": 160,
          "height": 247
        },
        "normalizedPlacement": {
          "x": 262,
          "y": 218,
          "width": 160,
          "height": 247
        },
        "sourceAnchor": {
          "bodyCenterX": 662,
          "feetBaselineY": 674
        },
        "rationale": "Next side-facing walk pose; assigned right by sheet order.",
        "warnings": []
      },
      "walk_right_b": {
        "row": 1,
        "col": 2,
        "index": 7,
        "sourceIndex": 7,
        "sourceRow": 1,
        "sourceCol": 2,
        "sourceRect": {
          "x": 793,
          "y": 397,
          "width": 397,
          "height": 396
        },
        "sourceAlphaBBox": {
          "x": 927,
          "y": 426,
          "width": 160,
          "height": 252
        },
        "normalizedPlacement": {
          "x": 264,
          "y": 213,
          "width": 160,
          "height": 252
        },
        "sourceAnchor": {
          "bodyCenterX": 1015,
          "feetBaselineY": 677
        },
        "rationale": "Final side-facing walk pose; assigned right by sheet order.",
        "warnings": []
      },
      "walk_up_a": {
        "row": 1,
        "col": 3,
        "index": 8,
        "sourceIndex": 8,
        "sourceRow": 1,
        "sourceCol": 3,
        "sourceRect": {
          "x": 1190,
          "y": 397,
          "width": 396,
          "height": 396
        },
        "sourceAlphaBBox": {
          "x": 1290,
          "y": 417,
          "width": 158,
          "height": 262
        },
        "normalizedPlacement": {
          "x": 279,
          "y": 203,
          "width": 158,
          "height": 262
        },
        "sourceAnchor": {
          "bodyCenterX": 1363,
          "feetBaselineY": 678
        },
        "rationale": "First back-facing/up walking pose.",
        "warnings": []
      },
      "walk_up_b": {
        "row": 1,
        "col": 4,
        "index": 9,
        "sourceIndex": 9,
        "sourceRow": 1,
        "sourceCol": 4,
        "sourceRect": {
          "x": 1586,
          "y": 397,
          "width": 397,
          "height": 396
        },
        "sourceAlphaBBox": {
          "x": 1666,
          "y": 414,
          "width": 159,
          "height": 266
        },
        "normalizedPlacement": {
          "x": 277,
          "y": 199,
          "width": 159,
          "height": 266
        },
        "sourceAnchor": {
          "bodyCenterX": 1741,
          "feetBaselineY": 679
        },
        "rationale": "Second back-facing/up walking pose.",
        "warnings": []
      }
    },
    "notes": [
      "Source alpha channel was used as-is; no rembg, background removal, or chroma key was run.",
      "All frames share a fixed normalized body center and feet baseline.",
      "Attack frames use lower-body alpha median anchors so weapon/effect pixels do not pull the body anchor.",
      "Side left/right categories preserve the source sheet order."
    ]
  },
  "wizard": {
    "image": "assets_v2/characters/classes/wizard_normalized.png",
    "textureKey": "class_wizard_sheet",
    "source": {
      "originalFile": "D:/Tools/rembg/bg_output/wizard.png",
      "copiedFile": "assets_v2/source_sheets/class_sprites/wizard.png",
      "sheetWidth": 1983,
      "sheetHeight": 793,
      "sourceColumns": 5,
      "sourceRows": 2,
      "splitMethod": "rounded proportional 5x2 cell boundaries from the source sheet dimensions"
    },
    "grid": {
      "columns": 5,
      "rows": 2,
      "cellWidth": 704,
      "cellHeight": 512,
      "sheetWidth": 3520,
      "sheetHeight": 1024
    },
    "anchor": {
      "bodyCenterX": 352,
      "feetBaselineY": 464
    },
    "frameOrder": [
      "attack_windup_left",
      "attack_release_left",
      "walk_down_a",
      "walk_down_b",
      "walk_left_a",
      "walk_left_b",
      "walk_right_a",
      "walk_right_b",
      "walk_up_a",
      "walk_up_b"
    ],
    "frames": {
      "attack_windup_left": {
        "row": 0,
        "col": 0,
        "index": 0,
        "sourceIndex": 0,
        "sourceRow": 0,
        "sourceCol": 0,
        "sourceRect": {
          "x": 0,
          "y": 0,
          "width": 397,
          "height": 397
        },
        "sourceAlphaBBox": {
          "x": 92,
          "y": 74,
          "width": 305,
          "height": 265
        },
        "normalizedPlacement": {
          "x": 156,
          "y": 200,
          "width": 305,
          "height": 265
        },
        "sourceAnchor": {
          "bodyCenterX": 288,
          "feetBaselineY": 338
        },
        "rationale": "First attack pose; character faces left.",
        "warnings": [
          "Alpha bbox touches source cell boundary; verify proportional split."
        ]
      },
      "attack_release_left": {
        "row": 0,
        "col": 1,
        "index": 1,
        "sourceIndex": 1,
        "sourceRow": 0,
        "sourceCol": 1,
        "sourceRect": {
          "x": 397,
          "y": 0,
          "width": 396,
          "height": 397
        },
        "sourceAlphaBBox": {
          "x": 397,
          "y": 75,
          "width": 396,
          "height": 264
        },
        "normalizedPlacement": {
          "x": 54,
          "y": 201,
          "width": 396,
          "height": 264
        },
        "sourceAnchor": {
          "bodyCenterX": 695,
          "feetBaselineY": 338
        },
        "rationale": "Second attack/release pose; effect extends left.",
        "warnings": [
          "Alpha bbox touches source cell boundary; verify proportional split."
        ]
      },
      "walk_down_a": {
        "row": 0,
        "col": 2,
        "index": 2,
        "sourceIndex": 2,
        "sourceRow": 0,
        "sourceCol": 2,
        "sourceRect": {
          "x": 793,
          "y": 0,
          "width": 397,
          "height": 397
        },
        "sourceAlphaBBox": {
          "x": 793,
          "y": 65,
          "width": 315,
          "height": 274
        },
        "normalizedPlacement": {
          "x": 132,
          "y": 191,
          "width": 315,
          "height": 274
        },
        "sourceAnchor": {
          "bodyCenterX": 1013,
          "feetBaselineY": 338
        },
        "rationale": "First front-facing walking pose in top row.",
        "warnings": [
          "Alpha bbox touches source cell boundary; verify proportional split."
        ]
      },
      "walk_down_b": {
        "row": 0,
        "col": 3,
        "index": 3,
        "sourceIndex": 3,
        "sourceRow": 0,
        "sourceCol": 3,
        "sourceRect": {
          "x": 1190,
          "y": 0,
          "width": 396,
          "height": 397
        },
        "sourceAlphaBBox": {
          "x": 1253,
          "y": 68,
          "width": 173,
          "height": 277
        },
        "normalizedPlacement": {
          "x": 267,
          "y": 188,
          "width": 173,
          "height": 277
        },
        "sourceAnchor": {
          "bodyCenterX": 1338,
          "feetBaselineY": 344
        },
        "rationale": "Second front-facing walking pose in top row.",
        "warnings": []
      },
      "walk_left_a": {
        "row": 0,
        "col": 4,
        "index": 4,
        "sourceIndex": 4,
        "sourceRow": 0,
        "sourceCol": 4,
        "sourceRect": {
          "x": 1586,
          "y": 0,
          "width": 397,
          "height": 397
        },
        "sourceAlphaBBox": {
          "x": 1624,
          "y": 68,
          "width": 184,
          "height": 275
        },
        "normalizedPlacement": {
          "x": 258,
          "y": 190,
          "width": 184,
          "height": 275
        },
        "sourceAnchor": {
          "bodyCenterX": 1718,
          "feetBaselineY": 342
        },
        "rationale": "First side-facing walk pose after down frames; assigned left by sheet order.",
        "warnings": []
      },
      "walk_left_b": {
        "row": 1,
        "col": 0,
        "index": 5,
        "sourceIndex": 5,
        "sourceRow": 1,
        "sourceCol": 0,
        "sourceRect": {
          "x": 0,
          "y": 397,
          "width": 397,
          "height": 396
        },
        "sourceAlphaBBox": {
          "x": 186,
          "y": 433,
          "width": 185,
          "height": 267
        },
        "normalizedPlacement": {
          "x": 259,
          "y": 198,
          "width": 185,
          "height": 267
        },
        "sourceAnchor": {
          "bodyCenterX": 279,
          "feetBaselineY": 699
        },
        "rationale": "Second side-facing walk pose; assigned left by sheet order.",
        "warnings": []
      },
      "walk_right_a": {
        "row": 1,
        "col": 1,
        "index": 6,
        "sourceIndex": 6,
        "sourceRow": 1,
        "sourceCol": 1,
        "sourceRect": {
          "x": 397,
          "y": 397,
          "width": 396,
          "height": 396
        },
        "sourceAlphaBBox": {
          "x": 552,
          "y": 424,
          "width": 173,
          "height": 276
        },
        "normalizedPlacement": {
          "x": 266,
          "y": 189,
          "width": 173,
          "height": 276
        },
        "sourceAnchor": {
          "bodyCenterX": 638,
          "feetBaselineY": 699
        },
        "rationale": "Next side-facing walk pose; assigned right by sheet order.",
        "warnings": []
      },
      "walk_right_b": {
        "row": 1,
        "col": 2,
        "index": 7,
        "sourceIndex": 7,
        "sourceRow": 1,
        "sourceCol": 2,
        "sourceRect": {
          "x": 793,
          "y": 397,
          "width": 397,
          "height": 396
        },
        "sourceAlphaBBox": {
          "x": 909,
          "y": 424,
          "width": 172,
          "height": 276
        },
        "normalizedPlacement": {
          "x": 266,
          "y": 189,
          "width": 172,
          "height": 276
        },
        "sourceAnchor": {
          "bodyCenterX": 995,
          "feetBaselineY": 699
        },
        "rationale": "Final side-facing walk pose; assigned right by sheet order.",
        "warnings": []
      },
      "walk_up_a": {
        "row": 1,
        "col": 3,
        "index": 8,
        "sourceIndex": 8,
        "sourceRow": 1,
        "sourceCol": 3,
        "sourceRect": {
          "x": 1190,
          "y": 397,
          "width": 396,
          "height": 396
        },
        "sourceAlphaBBox": {
          "x": 1263,
          "y": 413,
          "width": 161,
          "height": 288
        },
        "normalizedPlacement": {
          "x": 270,
          "y": 177,
          "width": 161,
          "height": 288
        },
        "sourceAnchor": {
          "bodyCenterX": 1345,
          "feetBaselineY": 700
        },
        "rationale": "First back-facing/up walking pose.",
        "warnings": []
      },
      "walk_up_b": {
        "row": 1,
        "col": 4,
        "index": 9,
        "sourceIndex": 9,
        "sourceRow": 1,
        "sourceCol": 4,
        "sourceRect": {
          "x": 1586,
          "y": 397,
          "width": 397,
          "height": 396
        },
        "sourceAlphaBBox": {
          "x": 1625,
          "y": 414,
          "width": 163,
          "height": 286
        },
        "normalizedPlacement": {
          "x": 269,
          "y": 179,
          "width": 163,
          "height": 286
        },
        "sourceAnchor": {
          "bodyCenterX": 1708,
          "feetBaselineY": 699
        },
        "rationale": "Second back-facing/up walking pose.",
        "warnings": []
      }
    },
    "notes": [
      "Source alpha channel was used as-is; no rembg, background removal, or chroma key was run.",
      "All frames share a fixed normalized body center and feet baseline.",
      "Attack frames use lower-body alpha median anchors so weapon/effect pixels do not pull the body anchor.",
      "Side left/right categories preserve the source sheet order."
    ]
  }
} as const;

export type CharacterSpriteClass = keyof typeof CHARACTER_SPRITES;
export type CharacterSpriteFrameName = keyof typeof CHARACTER_SPRITES["fighter"]["frames"];
